version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
    ECR_REPOSITORY: "sasisuseso-maker/api"
  secrets-manager:
    DOCKERHUB_USERNAME: "${DOCKERHUB_CREDENTIALS_SECRET_ARN}:DOCKERHUB_USERNAME"
    DOCKERHUB_PASSWORD: "${DOCKERHUB_CREDENTIALS_SECRET_ARN}:DOCKERHUB_PASSWORD"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - ECR_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:latest -f ./build/package/docker/Dockerfile --target deploy .
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG

cache:
  paths:
    - "/root/.m2/**/*"
