services:
  app:
    build:
      context: .
      dockerfile: ./build/package/docker/Dockerfile
      target: local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Tokyo
    container_name: sasisuseso-maker-dev
